### ISSUE TITLE
stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by meruiden** [Noxdew/git-locks-manager#143]
**Operating system**:  Windows

Whenever I open an Unreal Engine project (20+ GB), I get the error "stdout maxBuffer length exceeded" and nothing shows up.

![image](https://user-images.githubusercontent.com/8461537/216838204-77336d5d-d173-49aa-8f33-19707cd2969d.png)

**Comment by meruiden** [comment]
Hi, yeah we do have a .gitignore file. We only upload files that need to be uploaded, and most binary files are marked as lockable lfs.

**Comment by morwoen** [comment]
Cool, thanks for confirming. I'll try to replicate it and find a solution. If you find yourself finding a solution before me, contributions are always welcome 😁

**Comment by morwoen** [comment]
Hey @meruiden, I've just released a new version v1.0.4.

It changes from using `exec` to `spawn` which should remove the buffer size limit entirely. I wasn't able to reproduce it (turns out none of my projects have as many files as yours :D) so I can't say for certain that it fixes it.

Let me know if this fixes it :)

**Comment by morwoen** [comment]
Wee issue with the release, will redo it now

**Comment by morwoen** [comment]
Hey @meruiden, Did you get a chance to try the new release?
